export const eventTypes = [
  {
    id: 1,
    eventName: 'Community Day',
    imageName: 'community',
    lightBG: 'bg-secondary',
    darkBG: 'dark:bg-secondary-dark',
    edgeRadius: 'rounded-l-xl',
  },
  {
    id: 2,
    eventName: 'Workshops',
    imageName: 'workshop',
    lightBG: 'bg-primary',
    darkBG: 'dark:bg-primary-dark',
    edgeRadius: 'md:rounded-none rounded-r-xl',
  },
  {
    id: 3,
    eventName: 'Talks',
    imageName: 'talks',
    lightBG: 'bg-accent',
    darkBG: 'dark:bg-accent-dark',
    edgeRadius: 'md:rounded-none rounded-l-xl',
  },
  {
    id: 4,
    eventName: 'Panels',
    imageName: 'panels',
    lightBG: 'bg-black',
    darkBG: 'dark:bg-dark ',
    edgeRadius: 'md:rounded-none rounded-r-xl',
  },
  {
    id: 5,
    eventName: 'Networking Party',
    imageName: 'party',
    lightBG: 'bg-accent-2',
    darkBG: 'dark:bg-accent-2-dark',
    edgeRadius: 'md:rounded-none rounded-l-xl',
  },
  {
    id: 6,
    eventName: 'Office Hours',
    imageName: 'officehours',
    lightBG: 'bg-secondary',
    darkBG: 'dark:bg-secondary-dark',
    edgeRadius: 'rounded-r-xl',
  },
]
