import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            id="font-awesome-css"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Montserrat%3A100%2C300%2C400%2C500%2C600%2C700%2C900&amp;display=swap&amp;ver=6.0"
            id="montserrat-font"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Rubik%3A100%2C300%2C500%2C700%2C900&amp;display=swap&amp;ver=6.0"
            id="rubik-font"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
